spring:
  r2dbc:
    url: r2dbc:h2:mem:///librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  main:
    web-application-type: reactive

# Optional: logging
logging:
  level:
    root: INFO
    com.example.library: DEBUG

server:
  port: 8080
